ckb-next/ckb-next

- README.md
Corsair has announced the RGB version of the K68.
> Specify support for the K68 non-RGB version only

- src/ckb-daemon/ckb-daemon.pro
- src/ckb-daemon/dpi.c
- src/ckb-daemon/keymap.c
This fixes some undefined behaviour of endian-dependency and unaligned access, and enables `-Wcast-align` to avoid this happening again.
> Unaligned access fix

- src/ckb-daemon/usb_linux.c
For whatever reason the old code tried to guess the maximum length of each endpoint based on the device type and firmware version.
We can safely assume that the max length is MSG_SIZE (64), as the actual length of the URB read is indicated by urb->actual_length, which will always be ≤ MSG_SIZE.
Please test it against mice and NRGB devices to be sure that nothing broke.
> Don't try to guess the max URB buffer length

- src/ckb-daemon/usb_linux.c
Keyboards such as the original K70 RGB have a physical BIOS switch.
Attempting to reset them doesn't help in such cases.
> Don't try to reset devices in BIOS mode

- src/ckb/kbfirmware.cpp
Minor edit to prevent the GUI from throwing a warning when reading the firmware table.
> Skip BEGIN FW ENTRIES in the FW table

- src/ckb-daemon/devnode.c
- src/ckb/kb.cpp
- src/ckb/kb.h
- src/ckb/kbwidget.cpp
There's no point in letting people try to save to hardware by pressing the button, when it's unsupported either due to lack of interrupts (v3), or because of protocol changes (Platinum).
> Disable Save to Hardware button for unsupported devices

- src/ckb-daemon/keymap.c
- src/ckb-daemon/keymap.h
- src/ckb-daemon/usb.h
- src/ckb-daemon/usb_linux.c
- src/ckb-daemon/usb_mac.c
This PR cleans up EP usage in os_usbsend(), and also introduces IS_V3_OVERRIDE.
Interrupt reads, the K55, the Polaris, and the K68 (as well as probably all new devices) depend on this.
TODO: Add IS_V3(kb) that combines the fwversion check with the override.
Since it is a small enough change, it can be done afterwards, otherwise the above will need to be rebased yet again.
> Add IS_V3_OVERRIDE and clean up EP usage 

- src/ckb/kbbindwidget.ui
- src/ckb/kbwidget.cpp
- src/ckb/kbwidget.ui
- src/ckb/kperfwidget.ui
Due to inconsistent header height, the tab content would get
pushed to a different vertical position, looking inconsistent.
This was obvious when switching between the lighting and binding
tabs, as the on screen keyboard would have a different vertical
position.
A header label with the device name was also added in the Device
tab to improve consistency.
> Set minimum header height on GUI tab widgets

- src/ckb-daemon/structures.h
- src/ckb-daemon/usb.h
- src/ckb-daemon/usb_linux.c
Closes #51, which contains a really nice summary of the whole problem.
A mutex and a buffer are added to the usbdevice struct.
When usbsend is called with the is_recv flag, the mutex is locked.
The main thread listens for packets starting with 0x0e, copies them to the buffer and unlocks the mutex.
usbrecv waits for the mutex to be unlocked and then copies the buffer from usbdevice.
The above is all ignored, falling back to the old behaviour, when fwversion is lower than 1.3 which works only with URB Controls.
Ideally, the comments for the functions should be rewritten before merging this.
> Use URB Interrupts for all non-HID transfers

- src/daemon/device.h
- src/daemon/device_keyboard.c
- src/daemon/device_vtable.c
- src/daemon/keymap_patch.c
- src/daemon/structures.h
- src/daemon/usb.c
- src/daemon/usb.h
- src/daemon/usb_linux.c
- src/daemon/usb_mac.c
Since devices like the K90 use an entirely different protocol,
they should have a name reflecting that. This now means that "NRGB"
refers to a device which has controllable single-colour backlighting.
> Rename "NRGB" devices to "LEGACY"

- src/daemon/CMakeLists.txt
- src/daemon/device_keyboard.c
- src/daemon/device_mouse.c
- src/daemon/dpi.c
- src/daemon/firmware.c
- src/daemon/led_keyboard.c
- src/daemon/led_mouse.c
- src/daemon/led_mousepad.c
- src/daemon/profile_mouse.c
- src/daemon/protocol.h
- src/daemon/usb.h
Given how much more we know about the protocol compared to this time last year, I felt we should replace the magic numbers with #defines that gave a little more information about what the protocol is doing.
> Replace magic protocol numbers with defines

- src/gui/kbbindwidget.cpp
Adds a popup warning that shows up only when winlock is enabled on the current profile and the user selects a win key to bind.
> Add winlock warning

- src/gui/extrasettingswidget.cpp
- src/gui/extrasettingswidget.h
- src/gui/extrasettingswidget.ui
- src/gui/main.cpp
Adds the option in the GUI to introduce a 5 second delay on start.
Useful for some rare cases that we are unable to reproduce choppy animations on macOS.
> Add GUI start delay

- src/daemon/usb_linux.c
Hi all,
This pull request is the result of my bad experience with ckb-next. I use a custom configured kernel and I didn't compile uinput into kernel or as a module. I used quickinstall script to install ckb-next, which automatically enables and starts the systemd service. But this caused a huge problem for me, absence of uinput made ckb-next make my Corsair keyboard and mouse useless. Since I didn't have any other keyboard, mouse or bootable media around, I couldn't disable systemd service and I had to bring a keyboard from my office to home to just disable the service and debug it. While debugging it, I saw that I need uinput. I compiled uinput as a module and that fixed my problem.
This part seems like has already been marked with a todo item so decided to implement it. I don't know if …
> Make absence of uinput a fatal error

- src/daemon/led_keyboard.c
- src/daemon/protocol.h
I forgot to PR this and just rediscovered it on my laptop.
It lights up the K68 NRGB's winlock light on anything which isn't complete black, which is a hack, but the code is now in place should we decide to change that.
> K68 NRGB winlock fix

- src/gui/mainwindow.cpp
- src/gui/mainwindow.h
Adds a sigint/sigterm handler to the GUI to gracefully handle ^C, making sure all devices are switched back to HW mode.
Need to use sockets as per Qt documentation due to all Qt functions not being safe for use inside signal handlers.
https://doc.qt.io/qt-5/unix-signals.html
```
QEventLoop: Cannot be used without QApplication
QDBusConnection: system D-Bus connection created before QCoreApplication. Application may misbehave.
Path to settings: "/home/tatokis/.config/ckb-next/ckb-next.conf"
Scanning "/usr/local/libexec/ckb-next-animations/gradient"
Scanning "/usr/local/libexec/ckb-next-animations/heat"
Scanning "/usr/local/libexec/ckb-next-animations/mviz"
Scanning "/usr/local/libexec/ckb-next-animations/pinwheel"
Scanning "/usr/local/libexec/ckb-next-animations/rain"
Scanning …
```
> Add SIGINT/SIGTERM handler to GUI

- src/daemon/keymap.c
- src/daemon/keymap.h
- src/daemon/protocol.h
- src/daemon/usb.c
- src/daemon/usb.h
- src/daemon/usb_linux.c
- src/daemon/usb_mac.c
Now mac and linux input code is shared.
Input logic has been moved to keymap.c and functions have been split.
macOS USB code was also necessarily modified to handle interrupts as handled by the shared input code.
> Rework input/mac USB code

- src/gui/kbperf.cpp
- src/gui/kbperf.h
- src/gui/keyaction.cpp
- src/gui/mperfwidget.cpp
- src/gui/mperfwidget.h
- src/gui/mperfwidget.ui
Adds a simple indicator to the GUI showing the active DPI state.
Useful for when editing DPI stages and having the LED indicator disabled.
Code-wise, it adds a signal that gets emitted every time the DPI changes, and can be repurposed later for other uses.
> Add GUI DPI indicator

- ckb-next-dev-detect
- src/dev-detect/CMakeLists.txt
- src/gui/settingswidget.cpp
- src/gui/settingswidget.h
- src/gui/settingswidget.ui
This PR modifies dev-detect to not ask for any user input and write the report to `/tmp` when `--nouserinput` is specified.
Additionally, the script gets installed along with the GUI and daemon, and a button is added in the GUI under Settings to launch the script and generate a report.
When the report is successfully generated, the GUI tries to show the generated report in the default file manager.
> Dev detect in gui

- src/gui/rebindwidget.cpp
- src/gui/rebindwidget.ui
This PR changes the layout and the widgets used in the macro tab, fixing rendering issues on mac and other themes.
Before:
After:
Also fixes the bottom of the `tip` under the program tab being cut off.
> Rework macro tab

- CMakeLists.txt
- linux/debian/DOCKER/BUILD_CREATE_DOCKER.md
- linux/debian/DOCKER/Dockerfile
- linux/debian/DOCKER/entry_point.sh
- linux/debian/postinst
Hello,
I am a young software developer looking to get in some contributions to open code. I have created a Dockerscript that builds ckb-next in deb form for Ubuntu 18.04. The packages recommended came from looking up ldd on ckb-next and ckb-next-daemon and using apt-file to find corresponding dependencies.
Ideally, this can be used in a pipeline or something like that to enable people to install ckb-next and hopefully this can be added to Ubuntu universe. I would love to have comments or changes if that is necessary.
Kind regards,
Krish
> Created a Docker image that creates ckb_next debs for Ubuntu 18.04

- linux/udev/99-ckb-daemon.rules
This change addresses issue [212](https://github.com/ckb-next/ckb-next/issues/212)
This change creates symlinks in /dev/input/by-id to the event objects for each device. Each ckb device has one mouse and one keyboard event that have the same name and little to distinguish them from each other, so to handle this I appended the EV count to the end of the name. 7 is mouse and 120003 is keyboard. Since these event objects are technically not the actually device but more of a fake device to facilitate remapping I felt it was appropriate to leave `ckb` at the front of the name rather than the traditional `usb`.
This is the first time I've ever done a pull request so if I messed up in protocol somewhere I apologize.
> Update udev rules to create symlinks for devices

- src/gui/kb.cpp
- src/gui/kblight.cpp
- src/gui/kblight.h
This is needed as the daemon wipes the RGB data when deleting
and creating a new profile, resulting in a black keyboard when
switching to a static profile
> Force a frame to the daemon on profile switch

- src/gui/kbperf.cpp
- src/gui/kbperf.h
The correct solution would be to store the flag for each dpi in the stack, however there's no point in it as all the mice with the sniper button have an RGB indicator that can only display a single active DPI stage.
> Fix DPI indicator not switching to sniper/other

- src/libs/kissfft/CMakeLists.txt
This should fix issue #188 
See: https://cmake.org/cmake/help/latest/command/add_library.html
Library is meant to be build as static so mark it as so.
> ensure KissFFT is static

- src/daemon/command.c
- src/daemon/input.c
- src/daemon/profile.c
- src/gui/gradientbutton.cpp
- src/gui/keymap.cpp
- src/libs/ckb-next/include/ckb-next/animation.h
Hello again,
I have again done some general minor fixes across the code base. Mainly in regards to some of the errors shown in the pedantic flags.
Some of these errors are likely to cause undefined or weird behaviour. Such as on clang the use of designated initializers as that is a GCC only extension.
Mostly just fixed issues with respect to sscanf, but at least now the code compiles under pedantic and seems to function.
I hope these changes are useful.
Kind regards,
Krish
> Improved compliance for ISO C for the codebase

- src/daemon/CMakeLists.txt
- src/libs/ckb-next/CMakeLists.txt
Use CMAKE_INSTALL_LIBDIR (provided by GNUInstallDirs module)
instead of hardcoding /usr/lib.
> Don't hardcode /usr/lib

- .github/ISSUE_TEMPLATE.md
I have simplified the issue template, and it no longer tells people to run curl | bash for dev detect, instead instructing them to click the Generate Report button in the GUI.
There were also some minor wording changes.
> Reword and simplify the issue template

- src/daemon/firmware.c
- src/daemon/structures.h
- src/daemon/usb.c
- src/daemon/usb.h
- src/daemon/usb_linux.c
- src/gui/fwupgradedialog.cpp
- src/gui/kb.h
- src/gui/kbfirmware.cpp
- src/gui/kbfirmware.h
The reason for this is that the usb id for the Y730 is 0xc935, which doesn't fit in a signed short.
https://github.com/ckb-next/ckb-next/issues/330#issuecomment-451611244
That said, I'm not sure why they were a signed shorts in the first place. Both VID/PID are unsigned 16 bit numbers.
Tested minimally, but everything seems to function, including firmware updates.
> Convert usb ids to unsigned shorts

- src/daemon/command.c
- src/daemon/command.h
- src/daemon/device_vtable.c
- src/daemon/main.c
- src/daemon/notify.c
- src/daemon/notify.h
As discussed in `#ckb-next` on friday the 25. january of 2019, the restart
functionality is ok to be remove.
This commit basically reverts the function to restart the daemon which
was introduced in 64bebfef. This decision was based on the fact, that
this functionality is a) not widespreadedly enough used to b) justify
the suboptimal implementation (and its impact on the debugging).
> Remove restarting capabilities

- src/daemon/includes.h
- src/daemon/main.c
- src/daemon/usb.h
- src/daemon/usb_linux.c
- src/daemon/usb_mac.c
This commit introduces a safer signal handling routine by splitting this
workflow into catching and handling of signals. In the catching routine
no unsafe function call is allowed (signal-safety(7)).
The general idea is generate a local socketpair (acting as an anonymous
pipe) that is written to with the caught signal type in the direct
sighandler routine. The calling of the routine that actually handles the
interrupts is elevated to the main loops, where the pipe is monitored.
As soon as data is available on the pipe it is read and the
sighandling-routine is called manually. This allows for greater freedom
of function calls to handle the signal with.
- Create anonymous socket pair for sending/receiving intent, only setup
signal handlers if the socket pair exists.
- Call `write` to sender …
> Improve safety of signal handling

- src/daemon/usb_mac.c
The segfault was based on a race condition between resetting/closing of
one of the attached devices, a subsequent input event that was handled
by another device's CFRunLoop callback, and a mutex lock.
Fix:
- Listen for `reset_stop` - which is set by `quit` when shutting down
the daemon - to stop processing input urbs.
> Fix segfault on macOS when quitting

- src/gui/extrasettingswidget.cpp
- src/gui/extrasettingswidget.h
- src/gui/extrasettingswidget.ui
- src/gui/kblightwidget.cpp
- src/gui/kblightwidget.h
- src/gui/kblightwidget.ui
This PR amends the GUI to automatically suspend the preview animation:
- Suspend preview animation if window is not active,
- resume the preview animation as soon as the window comes into focus again.
- Additionally the `showAnimBox` element and its `toolTip` property were amended to display the new feature.
> Issue 408/suspend preview animation

- src/daemon/usb.c
- src/daemon/usb.h
Quick patch, adds Pro model id to IS_HARPOON.
I don't see any differences between PRO and non-PRO other than sensor (6000dpi vs 12000dpi).
No extensive testing done; works on my mouse and shouldn't break anything.
Firmware update thing should maybe be also updated
[ckb-next-dev-detect](https://turtleb01.github.io/ckb-next-dev-detect.txt) if somebody needs this
I'm new to Github, sorry if I'm doing something wrong.
> Harpoon RGB PRO support

- src/gui/animdetailsdialog.ui
Descripton -> Description as noticed by lintian.
```
I: ckb-next: spelling-error-in-binary usr/bin/ckb-next Descripton Description
N: 
N:    Lintian found a spelling error in the given binary. Lintian has a list
N:    of common misspellings that it looks for. It does not have a dictionary
N:    like a spelling checker does.
N:    
N:    If the string containing the spelling error is translated with the help
N:    of gettext or a similar tool, please fix the error in the translations
N:    as well as the English text to avoid making the translations fuzzy. With
N:    gettext, for example, this means you should also fix the spelling
N:    mistake in the corresponding msgids in the *.po files.
N:    
N:    You can often find the word in the source code by running:
N:    
N:     grep -rw …
```
> Fixing spelling

- src/gui/kblight.cpp
I was just wondering if usage of QString::sprintf is really needed here. The same file contains a call to cmd.write() function that does not use QString::sprintf, just like in my change.
If I am missing something or toLatin1() is needed, I think cmd.write(QString("rgb 000000").toLatin1()); can be used instead.
> Replace deprecated QString::sprintf with a string

- linux/sysvinit/ckb-next-daemon.in
Bash functions are called without parenthesis.
> Resolve syntax error in ckb-next-daemon.in

- src/daemon/CMakeLists.txt
Add a CMake variable "SYSTEMD_UNIT_INSTALL_DIR" that can be manually set
to change where unit files are installed.
> Allow manual override of systemd unit directory

- src/daemon/devnode.h
gcc-10 now defaults to -fno-common and does not automatically add extern
to variables declared in headers.
https://gcc.gnu.org/gcc-10/porting_to.html
Signed-off-by: Erik Zeek <zeekec@gmail.com>
> Fix gcc-10/-fno-common error

- src/daemon/usb.c
- src/daemon/usb.h
This is #556 with the mouse in `V3_OVERRIDE` instead of `V2_OVERRIDE`.
Closes #552.
> Scimitar Elite support

- src/daemon/usb.c
- src/daemon/usb.h
I have tested the K63 Wireless support on my keyboard. I don't know why by my unit has different ID's than the existing defines:
- on usb cable 0x1b8c
- on usb dongle 0x1b8f
> add K63 Wireless Keyboard IDs. Part Number: CH-9145030-NA

- quickinstall
Resolves issue #592 by using parameter expansion that resolves when JOBS is explicitly set as an environment variable.
> Add JOBS env var for quickinstall

- src/gui/kbperf.cpp
- src/gui/kbperf.h
- src/gui/media.h
- src/gui/media_linux.cpp
- src/gui/media_mac.m
This is the first half (backend part) for #561, adding the code to store a default mute device in the profile, show the mute state based on this device and mute the correct device when the button is pressed.
I submit this part as a separate PR so that it can be taken into account when making changes (kbperf.cpp seeing those more often).
The UI for selecting the device is an ongoing discussion in #561
> Backend: Select device for mute indicator

- src/daemon/command.c
- src/daemon/device.c
- src/daemon/device.h
- src/daemon/input.c
- src/daemon/input.h
- src/daemon/main.c
- src/daemon/structures.h
- src/daemon/usb_linux.c
- src/daemon/usb_mac.c
The current code limits one macro invocation per 500 ms, even if the button the macro is bound to is release and pressed again.  This breaks convention---typically, users expect that releasing and depressing a button will cause the effect to be applied again.  The repeat delay is only expected if the button is held down continuously.
This patch tracks whether the macro trigger is released, and, if so, triggers the macro again, immediately (actually within ~1ms).  During long macro executions, a key release-press cycle can "queue up" up to one immediate additional invocation.
I'm currently running this.  I don't use LED animations (I actually use ckb-next to turn them off entirely).
> Allow for faster repeated macro calls

- src/daemon/bragi_common.c
- src/daemon/bragi_common.h
- src/daemon/bragi_proto.h
- src/daemon/keymap.c
- src/daemon/keymap_patch.c
- src/daemon/led_bragi.c
- src/daemon/usb.c
- src/daemon/usb.h
- src/gui/keymap.cpp
- src/gui/keymap.h
- src/gui/keywidget.cpp
A limitation ATM is that the wheel LED can be adjusted in brightness
but not color in SW mode. For HW mode the locations for the DPI colors
has been found.
As my goal with writing this was just to be able to switch the LED off
that solves what i need.
Signed-off-by: Michael Niedermayer <michael@niedermayer.cc>
> Add KATAR_PRO_XT

- src/daemon/keymap_patch.c
- src/daemon/led_bragi.c
- src/daemon/usb.c
- src/daemon/usb.h
This pull request adds support to the Corsair Katar PRO mice.
The device is very very similar to Katar PRO XT, so we can just add support to it in the daemon and use the XT's patches and name for keymapping. 
I'm currently using it and it's working just fine (both with GUI open and closed).
closes #780
> Add Katar PRO support

- src/daemon/includes.h
- src/daemon/input_linux.c
- src/daemon/usb.c
- src/daemon/usb.h
- src/daemon/usb_linux.c
- src/daemon/usb_mac.c
I have a Scimitar Pro, and have been experiencing issues around waking from suspend, similar to what is reported in e.g. #456, #652. It also occasionally completely locks up the daemon, and the system hangs indefinitely when trying to shut down (only SysRq / hard reboot works).
After a couple days of debugging, I isolated two mostly separate issues.
Sometimes when waking from suspend, I get this in `dmesg`:
<details>
<summary>dmesg output</summary>
```
[  104.480212] BUG: unable to handle page fault for address: 00000000000028a8
[  104.480231] #PF: supervisor write access in kernel mode
[  104.480239] #PF: error_code(0x0002) - not-present page
[  104.480248] PGD 0 P4D 0 
[  104.480260] Oops: 0002 [#1] PREEMPT SMP NOPTI
[  104.480272] CPU: 0 PID: 414 Comm: suspend Tainted: G           OE …
```
> Fix issues with suspend wakeup on Linux

- src/gui/kb.cpp
Initialize to zero at declaration to remove warnings:
```
/home/eric/src/ckb-next/src/gui/kb.cpp: In member function ‘void Kb::readNotify(const QString&)’:
/home/eric/src/ckb-next/src/gui/kb.cpp:742:24: warning: ‘y’ may be used uninitialized in this function [-Wmaybe-uninitialized]
742 |                 int x, y;
|                        ^
/home/eric/src/ckb-next/src/gui/kb.cpp:742:21: warning: ‘x’ may be used uninitialized in this function [-Wmaybe-uninitialized]
742 |                 int x, y;
|                     ^
```
> Fix maybe-uninitialized warning

- src/daemon/usb.c
- src/gui/keymap.cpp
- src/gui/keymap.h
K63 wireless layout should be the same as K65 including the existence of a JP variant.
Discussed in https://github.com/ckb-next/ckb-next/issues/74. Only the wired K63 does not have the FN key.
> K63 wireless layout should be the same as K65

- .github/actions/cmake/build/action.yml
- .github/actions/cmake/install/action.yml
- .github/actions/cmake/package/action.yml
- .github/actions/dependencies/install/action.yml
- .github/actions/dependencies/install/apt-get/action.yml
- .github/actions/dependencies/install/pacman/action.yml
- .github/actions/dependencies/install/yum/action.yml
- .github/actions/upload-package/action.yml
- .github/workflows/build.yml
- .gitignore
This adds automated building and packaging of `ckb-next` for the following Linux distibutions using GitHub Actions:
- `almalinux:8`
- `amazonlinux:2`
- `archlinux:latest`
- `debian:10`
- `debian:11`
- `fedora:35`
- `fedora:36`
- `rockylinux:8`
- `ubuntu:20.04`
- `ubuntu:22.04`
This should help in discovering build errors for those distributions.
I didn't see any unit tests or anything to run, so it runs `ckb-next-daemon --help` as at least very basic test.
Here's an example of what a workflow run looks like:
https://github.com/hummeltech/ckb-next/actions/runs/2543736710
> Add GitHub Actions to test building and packaging

- src/gui/macrotablemodel.cpp
This fixes a bug in the macro functionality when using a backslash on ISO keyboards. Prior to this the string parser would think keys with an underscore were invalid.
Resolves: #905
> Add '_' to the regex for the macro string parser

- linux/openrc/ckb-next-daemon.in
The original version reimplemented `start()` and `stop()` circumvented the added logic in the default ones.
This simplifies the file and allows the user to configure the service in `/etc/conf.d/cbk-next-daemon`.
One example would be:
```sh
command_args="--enable-experimental"
```
> OpenRC: rework init.d file

- src/daemon/keymap_patch.c
- src/daemon/led_bragi.c
- src/daemon/usb.c
- src/daemon/usb.h
- src/daemon/usb_bragi.c
- src/gui/kbperf.cpp
- src/gui/keymap.cpp
- src/gui/keymap.h
- src/gui/keywidget.cpp
This adds support for the K70 RGB TKL Champion Series keyboard.  Product page is here: https://www.corsair.com/us/en/Categories/Products/Gaming-Keyboards/RGB-Mechanical-Gaming-Keyboards/K70-RGB-TKL-CHAMPION-SERIES-Mechanical-Gaming-Keyboard/p/CH-9119014-NA
Its interface is fairly similar to the K100, but its key layout is closer to the K63.
I've tested this with my own keyboard, and everything seems fully functional.
Fixes #745
> Add support for the K70 RGB TKL

- src/daemon/device_bragi.c
- src/daemon/keymap_patch.c
- src/daemon/led_bragi.c
- src/daemon/usb.c
- src/daemon/usb.h
Some K100 devices identify on different product IDs. This commit introduces support for a known optical variant.
Key points for this commit are:
- Introduction of a new product ID 0x1bc5 as P_K100_OPTICAL_VARIANT
- This variant uses the more common endpoints 0x4 and 0x84
- This variant returns 0x06 as "not supported" instead of the anticipated 0x01 for switching bragi method.
> RGB support for k100 optical variant

- src/gui/xcb/xwindowdetector.cpp
This is needed because xcb_connect returns a valid value even if it fails.
Therefore we need to use xcb_connection_has_error() to check for failure.
Resolves #1000
> gui: Add error handling for xcb_connect

- quickinstall
- `if -n` can be used instead of `if ! -z` to avoid additional negation.
- `read` can be used without a name since the name is unused
Issues raised by [`shellcheck`](https://github.com/koalaman/shellcheck)
> Trivial: Fix `shellcheck` issues in `quickinstall`

- src/gui/ckbsettingswriter.cpp
The differing definitions between ckbsettingswriter.cpp and ckbsettings.cpp trigger compilation errors with -Werror=odr.
> ckbsettingswriter: mirror QT version guards from ckbsettings

- src/gui/kb.cpp
This fixes crashing with SIGPIPE on device disconnection.
Fixes #1004.
> Do not write to removed cmdpath

- src/daemon/device_bragi.c
- src/daemon/keymap.c
https://github.com/ckb-next/ckb-next/issues/1102
When discussing the issue where my ABNT layout K60 wasn't reading the slash/interrogation key in the IRC, KitsuWhooa directed me through testing the keyboard and we arrived at this edit, which enabled the slash key while the GUI is running.
> Starting implementation of slash key (ABNT layout)

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/new-device-request.yml
The "Generated Report" section was given a default value rather than a placeholder. This allows users to bypass it as a required field. My ide also deleted ending white-space which I figured inst an issue.
> Modify issue templates to require a generated report.
